
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import INSERT, Tk, Canvas, Entry, Text, Button, PhotoImage, ttk
import operaciones_json

from PIL import Image, ImageTk

class VerEmprendedores:

    def __init__(self, master):
        self.master = master
        self.images = []
        self.canvas = None
        self.crear_interfaz()
        self.center_window()

    def center_window(self):
        window_width = self.master.winfo_reqwidth()
        window_height = self.master.winfo_reqheight()
        position_top = int(self.master.winfo_screenheight() / 6 - window_height / 2)
        position_right = int(self.master.winfo_screenwidth() / 3 - window_width / 2)
        self.master.geometry("+{}+{}".format(position_right, position_top))
            
    def boton_Atras(self):
        self.master.destroy()
        root = Tk()
        from Principal_Agente import PrincipalAgente
        PrincipalAgente(root)
        print("button_Atras")

    def boton_CargarEmprendedores(self):
        #logica del boton
        Emprendedor= operaciones_json.read_json("Emprendedor.json")
        self.entry_1.insert(INSERT,Emprendedor)
        print("button_Cargar_Emprendedores")

    def cargar_datos(self, treeview, datos):
        for i in treeview.get_children():
            treeview.delete(i)

        claves = list(datos.keys())

        num_filas = len(datos[claves[0]])

        for i in range(num_filas):
            fila = [datos[clave][i] for clave in claves]
            treeview.insert("", "end", values=fila)

    def create_rectangle(self, x1, y1, x2, y2, **kwargs):
        if 'alpha' in kwargs:
            alpha = int(kwargs.pop('alpha') * 255)
            fill = kwargs.pop('fill')
            r, g, b = self.master.winfo_rgb(fill)
            fill = (r // 256, g // 256, b // 256, alpha)
            width = round(x2 - x1)
            height = round(y2 - y1)
            image = Image.new('RGBA', (width, height), fill)
            self.images.append(ImageTk.PhotoImage(image))
            self.canvas.create_image(x1, y1, image=self.images[-1], anchor='nw')
        self.canvas.create_rectangle(x1, y1, x2, y2, **kwargs)

    # ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame2")
    # window.geometry("782x587")


    def crear_interfaz(self):
        self.canvas = Canvas(
            self.master,
            bg="#FFFFFF",
            height=587,
            width=782,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        self.canvas.place(x=0, y=0)
        self.image_image_1 = PhotoImage(
            file=self.relative_to_assets("image_1.png"))
        self.image_1 = self.canvas.create_image(
            391.0,
            306.0,
            image=self.image_image_1
        )

        # self.canvas.create_rectangle(
        #     46.0,
        #     36.0,
        #     735.0,
        #     551.0,
        #     fill="#00796B",
        #     outline="")
        self.create_rectangle(46, 36, 735, 551, fill="#00796B", alpha=.8)

        self.canvas.create_rectangle(
            46.0,
            180.0,
            735.0,
            415.0,
            fill="#073131",
            outline=""
        )

        self.canvas.create_rectangle(
            37.0,
            447.0,
            746.0,
            510.0,
            fill="#000000",
            outline=""
        )

        self.button_image_1 = PhotoImage(
            file=self.relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=self.boton_CargarEmprendedores,
            relief="flat"
        )
        self.button_1.place(
            x=420.0,
            y=447.0,
            width=219.0,
            height=63.0
        )

        self.button_image_2 = PhotoImage(
            file=self.relative_to_assets("button_2.png"))
        self.button_2 = Button(
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=self.boton_Atras,
            relief="flat"
        )
        self.button_2.place(
            x=156.0,
            y=447.0,
            width=219.0,
            height=63.0
        )

        datos = operaciones_json.read_json("Emprendedor.json")
        print(datos)

        treeview = ttk.Treeview(self.master)
        
        columnas = list(datos.keys())
        treeview["columns"] = columnas
        treeview["show"] = "headings"  

        for columna in columnas:
            treeview.heading(columna, text=columna)
            treeview.column(columna, width=70, anchor="center")  

        self.cargar_datos(treeview,datos)
        treeview.place(
            x=0.0,
            y=200.0,
            width=800.0,
            height=193.0
        )

        self.image_image_2 = PhotoImage(
            file=self.relative_to_assets("image_2.png"))
        self.image_2 = self.canvas.create_image(
            124.0,
            109.0,
            image=self.image_image_2
        )

        self.image_image_3 = PhotoImage(
            file=self.relative_to_assets("image_3.png"))
        self.image_3 = self.canvas.create_image(
            391.0,
            105.0,
            image=self.image_image_3
        )

        self.master.geometry("782x587")
        self.master.configure(bg="#FFFFFF")
        self.master.resizable(False,False)

    def relative_to_assets(self, path: str) -> Path:
        assets_path = Path(__file__).parent / "assets" / "frame2"
        return assets_path / path
    
if __name__ == "__main__":
    window = Tk()
    app = VerEmprendedores(window)
    window.mainloop()   